"""
Django settings for Auth_Project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import ssl
import smtplib
from django.core.mail.backends.smtp import EmailBackend

# --- Python 3.12 SMTP Patch Start ---
def patched_open(self):
    if self.connection:
        return False
    try:
        self.connection = smtplib.SMTP(self.host, self.port, timeout=self.timeout)
        if self.use_tls:
            # Python 3.12 mein keyfile/certfile argument error deta hai
            # Isliye hum sirf starttls() call kar rahe hain
            self.connection.starttls() 
        if self.username and self.password:
            self.connection.login(self.username, self.password)
        return True
    except Exception:
        if self.fail_silently:
            return False
        raise

# Django ke default email backend ko hamare patched version se replace kar rahe hain
EmailBackend.open = patched_open
# --- Python 3.12 SMTP Patch End ---

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fWynPRmtdFQt1i4N7zlS1EkLVOQGdBOOKa3ESBj_o8Fmx1GYArETag2WGNa1WORd8Lc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Development ke liye True hona chahiye

ALLOWED_HOSTS = ['*']  # Local testing ke liye sab allowed

# Security settings (Local development me False rakhein)
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'Auth_App',

]


AUTH_USER_MODEL = 'Auth_App.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Auth_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Auth_Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
"""import certifi
ca = certifi.where()
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'djongo_mongo_auth',
        'CLIENT': {
           'host': 'mongodb+srv://vt464670_db_user:tGWT0e9Wdl6tCiC2@cluster0.hlj8gb9.mongodb.net/djongo_mongo_auth?retryWrites=true&w=majority&tlsAllowInvalidCertificates=true',
           'tlsCAFile': ca
        }
    }
}"""
# settings.py mein is tarah modify karein


# Development ke liye SQLite use kar rahe hain
# Production mein MongoDB use kar sakte ho
"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

# Agar MongoDB use karna hai to ye settings use karo (MongoDB Atlas):

import certifi
ca = certifi.where()
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'djongo_mongo_auth',
        'CLIENT': {
            'host': 'mongodb+srv://vt464670_db_user:tGWT0e9Wdl6tCiC2@cluster0.hlj8gb9.mongodb.net/djongo_mongo_auth?retryWrites=true&w=majority&tlsCAFile=' + certifi.where(),
        }
    }
}


            
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # Yeh line add karein
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Render ke liye zaruri


from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Django Auth API',
    'DESCRIPTION': 'Auth App API documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# settings.py mein
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
AUTH_USER_MODEL = 'Auth_App.User'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'vt464670@gmail.com'
EMAIL_HOST_PASSWORD = 'nczgwweqcanuoafs'
DEFAULT_FROM_EMAIL = 'Django_OTP_API <vt464670@gmail.com>'

#DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
# settings.py ke niche check karein
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
SILENCED_SYSTEM_CHECKS = ["mongodb.E001"]